"""moods and sessions

Revision ID: 424323e82233
Revises: dbc174aaea6b
Create Date: 2026-07-19 15:54:57.594322

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "424323e82233"
down_revision: str | None = "dbc174aaea6b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "affinity_map",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("mapping", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "mood_description",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("name"),
    )
    op.create_table(
        "session",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("mood", sa.String(), nullable=False),
        sa.Column("started_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("session", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_session_started_at"), ["started_at"], unique=False)

    op.create_table(
        "play",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("session_id", sa.String(), nullable=False),
        sa.Column("instance_id", sa.String(), nullable=False),
        sa.Column("release_id", sa.String(), nullable=False),
        sa.Column("played_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["session.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("play", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_play_release_id"), ["release_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_play_session_id"), ["session_id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("play", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_play_session_id"))
        batch_op.drop_index(batch_op.f("ix_play_release_id"))

    op.drop_table("play")
    with op.batch_alter_table("session", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_session_started_at"))

    op.drop_table("session")
    op.drop_table("mood_description")
    op.drop_table("affinity_map")
    # ### end Alembic commands ###
