"""recommendations

Revision ID: 5f445714ec8b
Revises: 424323e82233
Create Date: 2026-07-19 16:03:13.384062

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "5f445714ec8b"
down_revision: str | None = "424323e82233"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "recommendation_window",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("days", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "recommendation",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("session_id", sa.String(), nullable=False),
        sa.Column("release_id", sa.String(), nullable=False),
        sa.Column("generated_at", sa.DateTime(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["session_id"],
            ["session.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("recommendation", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_recommendation_generated_at"), ["generated_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_recommendation_release_id"), ["release_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_recommendation_session_id"), ["session_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("recommendation", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_recommendation_session_id"))
        batch_op.drop_index(batch_op.f("ix_recommendation_release_id"))
        batch_op.drop_index(batch_op.f("ix_recommendation_generated_at"))

    op.drop_table("recommendation")
    op.drop_table("recommendation_window")
    # ### end Alembic commands ###
