"""records: release and instance

Revision ID: dbc174aaea6b
Revises: 33b4a35f9a67
Create Date: 2026-07-19 15:45:07.305282

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "dbc174aaea6b"
down_revision: str | None = "33b4a35f9a67"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "release",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("artist", sa.String(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("year", sa.Integer(), nullable=True),
        sa.Column("styles", sa.JSON(), nullable=False),
        sa.Column("cover_path", sa.String(), nullable=True),
        sa.Column("cover_source_url", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "instance",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("release_id", sa.String(), nullable=False),
        sa.Column("pressing_release_id", sa.Integer(), nullable=False),
        sa.Column("is_playable", sa.Boolean(), nullable=False),
        sa.Column(
            "retirement_status",
            sa.Enum("active", "pending", "retired", name="retirementstatus"),
            nullable=False,
        ),
        sa.Column("description", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["release_id"],
            ["release.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("instance", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_instance_release_id"), ["release_id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("instance", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_instance_release_id"))

    op.drop_table("instance")
    op.drop_table("release")
    # ### end Alembic commands ###
